
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/cody/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.31.5/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Linux - 6.8.0-90-generic - x86_64
...
